version: '3.9'
services:
  ubuntu:
    image: matheusgigliotti/app-ubuntu-py
    container_name: ubt
    build:
      context: .
      dockerfile : Dockerfile
    command: python3 app.py
    ports:
      - 8080:5000